name: Scheduled Job

on:
  schedule:
    - cron: '0 10 * * *'  # 每天 UTC 时间 10:00 触发

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "定时任务触发了，当前时间是 $(date -u)"
