name: Run Nuclei POC Gather

on:
  schedule:
    # 每天凌晨1点执行一次，时间可根据需要修改
    - cron: '0 1 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-poc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    - name: Run Nuclei POC Gather script
      run: |
        python NucleiPocGather.py

    - name: Commit and Push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && echo "No changes to commit" || (git commit -m "Auto update POC files" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
